arch:
- amd64
os: linux
dist: bionic
language: shell

jobs:
  include:
  - script:
    - docker build -t jchorl/etcher:$TRAVIS_COMMIT etcher
    - docker build -t jchorl/spotifyd:$TRAVIS_COMMIT spotifyd
    - docker build -t jchorl/spotify-tui:$TRAVIS_COMMIT spotify-tui
    - docker build -t jchorl/transmission:$TRAVIS_COMMIT transmission
  - arch: arm64
    script:
    - docker build -t jchorl/spotifyd:$TRAVIS_COMMIT-arm32v7 -f spotifyd/Dockerfile.arm32v7 spotifyd
    - docker build -t jchorl/pihole-exporter:$TRAVIS_COMMIT-arm32v7 -f pihole-exporter/Dockerfile.arm32v7 pihole-exporter

deploy:
- provider: script
  script: bash scripts/deploy.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master

env:
  global:
  - DOCKER_USERNAME=jchorl
  - secure: ThAwhGHSboQV7noZk9uf05sYKJW9e/w4cJVPmd4ETWct7sNW+/9/gaGM3DPKGC9FMc3OZY2oPTCEOkAcfUBqQXSHPIMUmpLu4FLBSiAR+dYLhMR9r+Z95p3D5NkIbTsEOi0LNb9nacnIw7A/3cL+d8M5iMd8z9k+P3EBqL0alibF7sdzOSd4oaufE96Rt7qv9A/Bkh2EB2xSTj0T9uKnBzmIiA6zoT8vNfM4jFDUX3FIioEPy7Vu0TQx8a5E+6IOl8+ELwXQ3bVco0P5VITIaXp+BsYrHpSI3w/h7MK5lO2JTRP4wnQcc8rwCZ38sCgJFdfYmQPUJ4A0fyRMMxQnDjU0psmuXaJfGBlFvq/aBMNxCU27JF+2HZKGNl+z2KbmWNTsGDtkqfPZnQuI12+kZiPfTdFhxiXSfSrQP1disLY7Uy/jobyQ2lx5DwGtuG++8jlCH6fyfJJFiqWZB9iWR16U1pN5fwE4OE0z1vlxKejE2UA5n7FY5XurxVog3onMezvdTQfrqUBK9law7ywNvRQYAnKTaQq+4wLjDVau/hKlnE5GnUOWDexmQOhkDx/Cpt6zbUAfHbGXygH49hbxHU3KId/J6ddJmSGSTVsB74CvmQYVbeoAR0D3GWuwB/wKLnTLGGc1SUqKsZlWpDkAd05nFLIrTnaQlGwsYFSkNt0=
