FROM arm32v7/golang:alpine as builder

RUN apk update && \
    apk --no-cache add git alpine-sdk

WORKDIR /go/src/github.com/eko/
RUN git clone --depth 1 https://github.com/eko/pihole-exporter.git
WORKDIR /go/src/github.com/eko/pihole-exporter

RUN GO111MODULE=on go mod vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -ldflags '-s -w' -o binary ./

FROM scratch
COPY --from=builder /go/src/github.com/eko/pihole-exporter/binary /pihole-exporter
ENTRYPOINT ["/pihole-exporter"]
